export const MATERIAL_TWEAKS = [
  {
    id: "background",
    materialNameIncludes: ["background", "backdrop", "panorama", "sky"],
    meshNameIncludes: ["background", "backdrop", "panorama", "sky", "dome"],
    brightness: 1.12,
    saturation: 0.82,
    excludeFromGameplayBounds: true,
  },
  {
    id: "floorSurface",
    materialNameIncludes: ["floor", "parquet", "hardwood", "wood_floor", "woodfloor"],
    meshNameIncludes: ["floor", "parquet", "hardwood", "wood_floor", "woodfloor"],
    bakedTextureAnisotropy: 16,
  },
];

export const MATERIAL_PRESETS = {
  alphaCutoff: 0.5,
  glassMaterial: {
    defaultRoughness: 0.1,
    ior: 1.01,
    transmission: 0.95,
    thickness: 0.0,
    envMapIntensity: 1.0,
  },
  glassUvChannels: {
    color: 1,
    roughness: 1,
    normal: 1,
  },
  windowsMaterial: {
    ior: 1.5,
    transmission: 0.0,
    opacity: 0.08,
    roughness: 0.01,
  },
  translucency: {
    strength: 0.72,
    hueDegrees: -5,
    saturationBoost: 0.16,
    brightnessBoost: 0.18,
  },
  emissiveMaterial: {
    intensityMultiplier: 1.0,
  },
  fxAlphaCutoff: 0.05,
  fxUvChannels: {
    color: 0,
    alpha: 0,
  },
  fireVideo: {
    searchParam: "fireVideo",
    matchIncludes: ["fire", "flame", "ember"],
    blackPoint: 0.06,
    whitePoint: 0.34,
    brightnessBoost: 1.15,
    hueDegrees: -15,
    saturation: 1.04,
    value: 0.16,
  },
  useFallbackMapAlphaFromSeparateUv: false,
  foliageDisableMipmaps: false,
  foliagePremultiplyAlpha: true,
  foliageAnisotropy: 4,
  alphaCutoutUvChannels: {
    color: 1,
    alpha: 0,
  },
  reflectUvChannels: {
    color: 1,
    roughness: 0,
    metalness: 0,
    ao: 0,
    normal: 0,
  },
  reflectMaterial: {
    searchParam: "reflectEnv",
    envMapIntensity: 1.0,
    defaultRoughness: 0.0,
    defaultMetalness: 1.0,
    baseColorBoost: 2.2,
    ior: 1.5,
    specularIntensity: 1.0,
    envMapRotationDegrees: 90,
  },
  background: {
    hueDegrees: 0,
    saturation: 1.0,
    value: 1.0,
    gamma: 1.0,
    rotationDegreesPerMinute: 0,
    warpStrength: 0,
    warpScale: 24,
    warpSpeed: 0,
    shimmerStrength: 0,
    shimmerSpeed: 0,
  },
  sky: {
    hueDegrees: 0,
    saturation: 0.77,
    value: 1.15,
    gamma: 1.0,
  },
};
